filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/sample-app/*.log

output.elasticsearch:
  hosts: ["http://opensearch:9200"]
  # If security is enabled, add the following:
  username: "admin"
  password: "admin"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

